services:
  redis:
    image: redis:alpine

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
